version: "3.8"
services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: db_crud
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "5433:5432"
